package services.hpexstream.engine;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2019-03-20T22:07:25.783-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "urn:hpexstream-services/Engine", name = "EngineWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface EngineWebService {

    @WebMethod(operationName = "Compose")
    @Action(input = "urn:hpexstream-services/Engine:EngineWebService:ComposeRequest", output = "urn:hpexstream-services/Engine:EngineWebService:ComposeResponse", fault = {@FaultAction(className = EngineServiceException_Exception.class, value = "urn:hpexstream-services/Engine:EngineWebService:Compose:Fault:EngineServiceException")})
    @RequestWrapper(localName = "Compose", targetNamespace = "urn:hpexstream-services/Engine", className = "services.hpexstream.engine.Compose")
    @ResponseWrapper(localName = "ComposeResponse", targetNamespace = "urn:hpexstream-services/Engine", className = "services.hpexstream.engine.ComposeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public services.hpexstream.engine.EwsComposeResponse compose(
        @WebParam(name = "EWSComposeRequest", targetNamespace = "")
        services.hpexstream.engine.EwsComposeRequest ewsComposeRequest
    ) throws EngineServiceException_Exception;
}
