
package services.hpexstream.engine;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.2
 * 2019-03-20T22:07:25.745-05:00
 * Generated source version: 2.4.2
 */

@WebFault(name = "EngineServiceException", targetNamespace = "urn:hpexstream-services/Engine")
public class EngineServiceException_Exception extends Exception {
    
    private services.hpexstream.engine.EngineServiceException engineServiceException;

    public EngineServiceException_Exception() {
        super();
    }
    
    public EngineServiceException_Exception(String message) {
        super(message);
    }
    
    public EngineServiceException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public EngineServiceException_Exception(String message, services.hpexstream.engine.EngineServiceException engineServiceException) {
        super(message);
        this.engineServiceException = engineServiceException;
    }

    public EngineServiceException_Exception(String message, services.hpexstream.engine.EngineServiceException engineServiceException, Throwable cause) {
        super(message, cause);
        this.engineServiceException = engineServiceException;
    }

    public services.hpexstream.engine.EngineServiceException getFaultInfo() {
        return this.engineServiceException;
    }
}
